export const TODO_CREATE = 'TODO_CREATE'
export const TODO_COMPLETE = 'TODO_COMPLETE'
export const TODO_UNDO_COMPLETE = 'TODO_UNDO_COMPLETE'
export const TODO_DESTROY_COMPLETE = 'TODO_DESTROY_COMPLETE'